[model]
name = "moving-mnist"

[model.input_size]
height = 64
width = 64
channels = 1
sequence_length = 10

[model.output_size]
height = 64
width = 64
channels = 1
sequence_length = 10

[model.encoder]
kernel_size = [3,3]
layers = 3
filters = 64

[model.decoder]
kernel_size = [3,3]
layers = 3
filters = 64


[training]
max_epochs = 100
metrics = ['mae', 'mse', 'bmae', 'bmse']
optimizer = 'adam'


[mlflow]
experiment_name = "moving_mnist"
experiment_tracker = "Infoplaza MLFlow"


[visualize]
output_dir = '../../../../../logs/'