[model]
name = "SAT2RAD_UNET"

[model.input_size]
height = 256
width = 256
channels = 11
sequence_length = 8

[model.output_size]
height = 256
width = 256
channels = 1
sequence_length = 1

[model.encoder]
kernel_size = [3,3]
layers = 3
filters = 64

[model.decoder]
kernel_size = [3,3]
layers = 3
filters = 64


[training]
max_epochs = 100
metrics = ['mae', 'mse', 'bmae', 'bmse']
optimizer = 'adam'


[mlflow]
experiment_name = "sat2rad_unet"
experiment_tracker = "Infoplaza MLFlow"


[visualize]
output_dir = '../../../../../logs/'