[model]
name = "Binned SAT2RAD"

[model.input_size]
height = 256
width = 256
channels = 11
sequence_length = 5

[model.output_size]
height = 256
width = 256
channels = 1
sequence_length = 1

[model.encoder]
kernel_size = [3,3]
layers = 3
filters = 64

[model.decoder]
kernel_size = [3,3]
layers = 3
filters = 64

[model.training]
metrics = ['acc', 'precision', 'recall', 'exact', "f1", "jaccard"]


[training]
max_epochs = 100
metrics = ['mae', 'mse', 'bmae', 'bmse']
optimizer = 'adam'


[mlflow]
experiment_name = "sat2rad_binned_convlstm_attention"
experiment_tracker = "Infoplaza MLFlow"


[visualize]
output_dir = '../../../../../logs/'