[downloads]
skip = true
endpoint = 'https://ams3.digitaloceanspaces.com'
region = 'ams3'
bucket_name = 'infoplaza-data-scientist-m-bruder'
digital_ocean = true
directory = '../../data'
[downloads.range]
all = false
start = 2023-03-26T23:00:00
end = 2023-04-05T23:00:00

[satellite]
reader = "seviri_l1b_native"
channels = [
  "IR_016",
  "IR_039",
  "IR_087",
  "IR_097",
  "IR_108",
  "IR_120",
  "IR_134",
  "VIS006",
  "VIS008",
  "WV_062",
  "WV_073",
]

[satellite.folder]
original_path = "../../data/satellite"
save_path = "../../data/preprocessed/satellite"
file_ext = ".nat"

[satellite.output_size]
height = 256
width = 256

[satellite.reprojection]
skip = false
projection_string = "+proj=merc +lat_0=52.5 +lon_0=5.5 +ellps=WGS84"
# bottom left, top right
area = [0, 50, 10, 55]
resampler = "nearest"

[radar]
parameter = "reflectivity"
pixel_range = [0, 255]
save_path_bins = "../../data/preprocessed/radar-binned"
[radar.folder]
original_path = "../../data/radar"
save_path = "../../data/preprocessed/radar"
file_ext = ".h5"
[radar.output_size]
height = 256
width = 256
