[model]
name = "Sat2Rad One LSTM :grinning_face_with_sweat:"

[model.input_size]
height = 256
width = 256
channels = 11
sequence_length = 5

[model.output_size]
height = 256
width = 256
channels = 1
sequence_length = 1

[model.encoder]
kernel_size = [3,3]
layers = 1
filters = 128

[training]
max_epochs = 100
metrics = ['mae', 'mse', 'bmae', 'bmse']
optimizer = 'adam'


[mlflow]
experiment_name = "sat2rad_simplified_convlstm"
experiment_tracker = "Infoplaza MLFlow"


[visualize]
output_dir = '../../../../../logs/'